/*
 * File: app/view/mvc/Listeners.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.view.mvc.Listeners', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.mvc_listeners',

    requires: [
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.grid.feature.Grouping'
    ],

    title: 'Controller Listeners',
    store: 'mvc.Listeners',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'event',
                    text: 'Event Name',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'selector',
                    text: 'Selector',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'method',
                    text: 'Method Name',
                    flex: 1
                }
            ],
            features: [
                {
                    ftype: 'grouping'
                }
            ]
        });

        me.callParent(arguments);
    }

});