/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.controller.Main', {
    extend: 'Ext.app.Controller',

    init: function(application) {
        this.control({
            '#mainView' : {
                'afterrender' : this.onAppRender
            }
        });
    },

    onAppRender: function() {
        var app = this.getApplication();

        AI.util.InspectedWindow.eval(
            AI.util.InspectedWindow.getAppVersion,
            null,
            function (data) {
                var main = Ext.ComponentQuery.query('#mainView')[0];

                if (!data) {
                    main.disable();
                }
                else {
                    main.down('#AppDetails').setSource(data);

                    app.info = {
                        framework : data.extjs ? 'ext' : 'touch',
                        version   : data.extjs ? data.extjs.version : data.touch.version
                    };
                }
            }
        );
    }

});
