/*
 * File: app/store/Stores.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.store.Stores', {
    extend: 'Ext.data.Store',

    requires: [
        'AI.model.Store'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'AI.model.Store',
            storeId: 'Stores',
            data: [
                {
                    id: 'sequitur',
                    count: 819,
                    leaf: true
                },
                {
                    id: 'cum',
                    count: 393,
                    leaf: false
                },
                {
                    id: 'suscipit',
                    count: 186,
                    leaf: true
                },
                {
                    id: 'ii',
                    count: 932,
                    leaf: true
                },
                {
                    id: 'claram',
                    count: 741,
                    leaf: false
                },
                {
                    id: 'consectetuer',
                    count: 428,
                    leaf: true
                },
                {
                    id: 'demonstraverunt',
                    count: 535,
                    leaf: true
                },
                {
                    id: 'liber',
                    count: 121,
                    leaf: true
                },
                {
                    id: 'wisi',
                    count: 921,
                    leaf: true
                },
                {
                    id: 'feugiat',
                    count: 323,
                    leaf: true
                },
                {
                    id: 'parum',
                    count: 241,
                    leaf: false
                },
                {
                    id: 'eros',
                    count: 873,
                    leaf: false
                },
                {
                    id: 'facilisi',
                    count: 323,
                    leaf: true
                },
                {
                    id: 'qui',
                    count: 91,
                    leaf: true
                },
                {
                    id: 'typi',
                    count: 269,
                    leaf: false
                },
                {
                    id: 'parum',
                    count: 981,
                    leaf: false
                },
                {
                    id: 'duis',
                    count: 595,
                    leaf: false
                },
                {
                    id: 'magna',
                    count: 980,
                    leaf: false
                },
                {
                    id: 'consectetuer',
                    count: 911,
                    leaf: false
                },
                {
                    id: 'lius',
                    count: 934,
                    leaf: false
                },
                {
                    id: 'est',
                    count: 977,
                    leaf: false
                },
                {
                    id: 'dynamicus',
                    count: 589,
                    leaf: true
                },
                {
                    id: 'claritatem',
                    count: 855,
                    leaf: true
                },
                {
                    id: 'amet',
                    count: 808,
                    leaf: false
                },
                {
                    id: 'blandit',
                    count: 568,
                    leaf: true
                },
                {
                    id: 'sollemnes',
                    count: 124,
                    leaf: true
                },
                {
                    id: 'Claritas',
                    count: 984,
                    leaf: true
                },
                {
                    id: 'demonstraverunt',
                    count: 697,
                    leaf: false
                },
                {
                    id: 'typi',
                    count: 925,
                    leaf: true
                },
                {
                    id: 'lectores',
                    count: 122,
                    leaf: false
                },
                {
                    id: 'ipsum',
                    count: 913,
                    leaf: false
                },
                {
                    id: 'Lorem',
                    count: 723,
                    leaf: false
                },
                {
                    id: 'processus',
                    count: 168,
                    leaf: true
                },
                {
                    id: 'placerat',
                    count: 150,
                    leaf: true
                },
                {
                    id: 'facit',
                    count: 440,
                    leaf: true
                },
                {
                    id: 'per',
                    count: 155,
                    leaf: true
                },
                {
                    id: 'legentis',
                    count: 194,
                    leaf: false
                },
                {
                    id: 'Investigationes',
                    count: 777,
                    leaf: true
                },
                {
                    id: 'Claritas',
                    count: 472,
                    leaf: false
                },
                {
                    id: 'litterarum',
                    count: 585,
                    leaf: false
                },
                {
                    id: 'quis',
                    count: 627,
                    leaf: true
                },
                {
                    id: 'tincidunt',
                    count: 129,
                    leaf: false
                },
                {
                    id: 'consuetudium',
                    count: 967,
                    leaf: true
                },
                {
                    id: 'id',
                    count: 468,
                    leaf: true
                },
                {
                    id: 'ut',
                    count: 434,
                    leaf: true
                },
                {
                    id: 'Mirum',
                    count: 728,
                    leaf: false
                },
                {
                    id: 'videntur',
                    count: 702,
                    leaf: true
                },
                {
                    id: 'doming',
                    count: 33,
                    leaf: false
                },
                {
                    id: 'esse',
                    count: 854,
                    leaf: false
                },
                {
                    id: 'luptatum',
                    count: 607,
                    leaf: true
                }
            ]
        }, cfg)]);
    }
});