/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.controller.Main', {
    extend: 'Ext.app.Controller',

    init: function(application) {
        this.control({
            '#mainView' : {
                'afterrender' : this.onAppRender
            }
        });
    },

    onAppRender: function() {
        var getInfoFromInspectedWindow = function () {
            if (!window.Ext) {
                return false;
            }

            var v = Ext.versions.extjs;

            return {
                'Version' : v.version
            };
        };

        AI.util.InspectedWindow.eval(
            getInfoFromInspectedWindow,
            null,
            function (data) {
                var main = Ext.ComponentQuery.query('#mainView')[0];

                if (!data) {
                    main.disable();
                }
                else {
                    main.down('#AppDetails').setSource(data);
                }
            }
        );
    }

});
