/*
 * File: app/view/stores/RecordListTree.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.view.stores.RecordListTree', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.recordlisttreestore',

    requires: [
        'Ext.tree.View',
        'Ext.tree.Column'
    ],

    cls: 'treegrid',
    title: 'Store Records',
    hideHeaders: true,
    rowLines: true,
    store: 'stores.RecordsTree',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {
                stripeRows: true,
                rootVisible: false
            },
            columns: [
                {
                    xtype: 'treecolumn',
                    dataIndex: 'text',
                    emptyCellText: 'node text missing ...',
                    text: 'Text',
                    flex: 3
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'id',
                    text: 'ID',
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    }

});