/*
 * File: app/view/Components.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.view.Components', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.components',

    requires: [
        'AI.view.ComponentsTreeGrid',
        'Ext.tree.Panel',
        'Ext.tab.Panel',
        'Ext.grid.property.Grid',
        'Ext.tab.Tab',
        'Ext.layout.container.Border'
    ],

    initialLoad: false,
    itemId: 'ComponentInspector',
    layout: 'border',
    iconCls: 'icn-components',
    title: 'Components',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'componentstreegrid',
                    itemId: 'ComponentTree',
                    flex: 1,
                    region: 'center'
                },
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    region: 'east',
                    split: true,
                    itemId: 'ComponentDetails',
                    minWidth: 100,
                    activeTab: 0,
                    minTabWidth: 45,
                    items: [
                        {
                            xtype: 'propertygrid',
                            itemId: 'ComponentProps',
                            title: 'Properties',
                            source: {
                                
                            }
                        },
                        {
                            xtype: 'propertygrid',
                            itemId: 'ComponentMethods',
                            title: 'Methods',
                            source: {
                                
                            }
                        }
                    ]
                }
            ],
            listeners: {
                beforeadd: {
                    fn: me.onComponentInspectorBeforeAdd,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onComponentInspectorBeforeAdd: function(container, component, index, eOpts) {
        this.setTitle(AI.util.i18n.getMessage(this.title));

    }

});