/*
 * File: app/view/Events.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.view.Events', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.eventgrid',

    requires: [
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    title: 'Events',
    store: 'Events',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'type',
                    text: 'Type'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'target',
                    text: 'Target',
                    flex: 1
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'RecordEvents',
                            text: 'Record'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'StopRecording',
                            text: 'Stop Recording'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});