/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'AI.view.About',
        'AI.view.Components',
        'AI.view.Stores',
        'AI.view.Layouts',
        'AI.view.Events',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel'
    ],

    itemId: 'mainview',
    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'about'
                        },
                        {
                            xtype: 'components'
                        },
                        {
                            xtype: 'stores'
                        },
                        {
                            xtype: 'layouts'
                        },
                        {
                            xtype: 'eventgrid'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});