/*
 * File: app/view/MVC.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.view.MVC', {
    extend: 'Ext.container.Container',
    alias: 'widget.mvc',

    requires: [
        'AI.view.mvc.Listeners',
        'AI.view.mvc.Records',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.tree.Column',
        'Ext.grid.Panel'
    ],

    title: 'MVC',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'treepanel',
                    flex: 1,
                    title: 'Application Instance Details',
                    store: 'MVC',
                    rootVisible: false,
                    viewConfig: {

                    },
                    columns: [
                        {
                            xtype: 'treecolumn',
                            dataIndex: 'text',
                            text: 'Class Name',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'count',
                            text: 'Count'
                        }
                    ]
                },
                {
                    xtype: 'mvc_listeners',
                    hidden: true,
                    flex: 2
                },
                {
                    xtype: 'mvc_records',
                    hidden: true,
                    flex: 2
                }
            ]
        });

        me.callParent(arguments);
    }

});