/*
 * File: app/view/Records.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.view.Records', {
    extend: 'Ext.container.Container',
    alias: 'widget.records',

    requires: [
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.toolbar.Paging',
        'Ext.grid.property.Grid'
    ],

    itemId: 'StoreDetails',
    resizable: true,
    resizeHandles: 'n',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    itemId: 'RecordList',
                    title: 'Store Records',
                    store: 'Records',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            resizable: false,
                            dataIndex: 'id',
                            text: 'Record ID',
                            flex: 1
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            itemId: 'mypagingtoolbar',
                            width: 360,
                            displayInfo: true,
                            store: 'Records'
                        }
                    ]
                },
                {
                    xtype: 'propertygrid',
                    flex: 1,
                    itemId: 'RecordDetail',
                    resizable: true,
                    resizeHandles: 'w',
                    title: 'Record Details',
                    nameColumnWidth: '50%',
                    source: {
                        
                    }
                }
            ]
        });

        me.callParent(arguments);
    }

});