/*
 * File: app/model/stores/RecordDetail.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.model.stores.RecordDetail', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'text'
        },
        {
            name: 'value'
        },
        {
            convert: function(v, rec) {
                var value = rec.get('value');

                if (rec.data.id === 'root') {
                    return '';
                }

                if (value === null) {
                    return 'null';
                }

                /*
                // TODO: Date() check needs to be more accurate
                if (Ext.isDate(value) || (typeof value === 'string' && Date.parse(value))) {
                    return 'date';
                }
                */

                return typeof value;
            },
            name: 'type'
        }
    ]
});