/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.view.MainView', {
    extend: 'Ext.container.Viewport',

    itemId: 'mainView',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    itemId: 'menuPanel',
                    width: 150,
                    collapsible: true,
                    title: 'Menu',
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'ComponentsNav',
                                    text: 'Components'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'StoresNav',
                                    text: 'Stores'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'ProfilesNav',
                                    text: 'Profiles'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'ContentPanel',
                    layout: {
                        type: 'card'
                    },
                    items: [
                        {
                            xtype: 'treepanel',
                            itemId: 'ComponentsPanel',
                            title: 'Component Tree',
                            store: 'Components',
                            rootVisible: false,
                            useArrows: true,
                            viewConfig: {

                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            itemId: 'RefreshComponentTree',
                                            text: 'Refresh'
                                        }
                                    ]
                                }
                            ],
                            columns: [
                                {
                                    xtype: 'treecolumn',
                                    dataIndex: 'text',
                                    text: 'Component ID',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'xtype',
                                    text: 'XType',
                                    flex: 1
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'StoresPanel',
                            layout: {
                                align: 'center',
                                pack: 'center',
                                type: 'vbox'
                            },
                            title: 'About Us'
                        },
                        {
                            xtype: 'panel',
                            itemId: 'ProfilesPanel',
                            layout: {
                                align: 'center',
                                pack: 'center',
                                type: 'vbox'
                            },
                            title: 'Contact Us'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});